//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ECATSample.rc 使用
//
#define IDD_ECATSAMPLE_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       129
#define IDD_DIALOG_REGISTER             130
#define IDC_BTN_InitialCard             1000
#define IDC_BTN_FindSlave               1001
#define IDC_CBO_CardNo                  1002
#define IDC_EDIT_SlaveNum               1003
#define IDC_CBO_NodeID                  1004
#define IDC_CBO_CardNo2                 1004
#define IDC_CBO_SingleNo                1004
#define IDC_CHK_Timer                   1006
#define IDC_STATIC_POSE                 1007
#define IDC_STATIC_LENGTH               1008
#define IDC_STATIC_POSE2                1008
#define IDC_STATIC_X_VAL                1009
#define IDC_CHK_ABS                     1010
#define IDC_STATIC_Y_VAL                1010
#define IDC_STATIC_Z_VAL                1011
#define IDC_STATIC_ROLL_VAL             1012
#define IDC_STATIC_PITCH_VAL            1013
#define IDC_STATIC_YAW_VAL              1014
#define IDC_STATIC_SENSOR               1015
#define IDC_EDIT_X_VAL                  1016
#define IDC_BUTTON_TEST                 1017
#define IDC_STATIC_TEST                 1018
#define IDC_BUTTON2                     1019
#define IDC_BUTTON_TEST2                1019
#define IDC_BUTTON_EXIT                 1019
#define IDC_CHART_CTRL                  1020
#define IDC_STATIC_APP_STATUS           1021
#define IDC_STATIC_SHOW_INIT            1022
#define IDC_EDIT_MC                     1023
#define IDC_BUTTON_TEST3                1023
#define IDC_STATIC_SENSOR2              1024
#define IDC_STATIC_APP_TITLE            1024
#define IDC_CHK_SVON                    1025
#define IDC_SHOW                        1026
#define IDC_EDIT_MaxVel                 1027
#define IDC_BUTTON_TEST4                1027
#define IDC_BUTTON_STOP_TEST            1027
#define IDC_EDIT_Tacc                   1028
#define IDC_STATIC_ROLL_HZ              1028
#define IDC_EDIT_Tdec                   1029
#define IDC_STATIC_PITCH_HZ             1029
#define IDC_STATIC_YAW_HZ               1030
#define IDC_STATIC_X_HZ                 1031
#define IDC_STATIC_Y_HZ                 1032
#define IDC_STATIC_Z_HZ                 1033
#define IDC_EDIT_Y_VAL                  1034
#define IDC_EDIT_Z_VAL                  1035
#define IDC_EDIT_ROLL_VAL               1036
#define IDC_EDIT_Dist                   1037
#define IDC_EDIT_PITCH_VAL              1037
#define IDC_EDIT_YAW_VAL                1038
#define IDC_FRM_SET_VEL_PROF            1039
#define IDC_EDIT_X_HZ                   1039
#define IDC_EDIT_Y_HZ                   1040
#define IDC_EDIT_Z_HZ                   1041
#define IDC_EDIT_ROLL_HZ                1042
#define IDC_EDIT_PITCH_HZ               1043
#define IDC_EDIT13                      1044
#define IDC_EDIT_YAW_HZ                 1044
#define IDC_STATIC_PLATFORM             1045
#define IDC_EDT_STS_CMD                 1046
#define IDC_STATIC_SWITCH_STATUS        1046
#define IDC_STATIC_POLE_LENGTH          1047
#define IDC_STATIC_STATUS1              1048
#define IDC_EDT_STS_FBK                 1049
#define IDC_STATIC_STATUS2              1049
#define IDC_STATIC_STATUS3              1050
#define IDC_EDT_STS_IO                  1051
#define IDC_STATIC_STATUS4              1051
#define IDC_EDT_STS_MC                  1052
#define IDC_STATIC_STATUS5              1052
#define IDC_BTN_STOP                    1053
#define IDC_STATIC_ROLL_PHASE           1053
#define IDC_BTN_RESET                   1054
#define IDC_STATIC_PITCH_PHASE          1054
#define IDC_BTN_CONNECT                 1055
#define IDC_BTN_DISCONNECT              1056
#define IDC_BTN_SINGLE_UP               1057
#define IDC_BTN_SINGLE_DOWN             1058
#define IDC_STATIC_YAW_PHASE            1059
#define IDC_STATIC_X_PHASE              1060
#define IDC_FRM_STS                     1061
#define IDC_STATIC_Y_PHASE              1061
#define IDC_STATIC_Z_PHASE              1062
#define IDC_EDIT_X_PHASE                1063
#define IDC_EDIT_Y_PHASE                1064
#define IDC_EDIT_Z_PHASE                1065
#define IDC_EDIT_ROLL_PHASE             1066
#define IDC_EDIT_PITCH_PHASE            1067
#define IDC_EDIT_YAW_PHASE              1068
#define IDC_STATIC_STATUS6              1069
#define IDC_STATIC_PIC_POLE1            1070
#define IDC_STATIC_PIC_POLE2            1071
#define IDC_STATIC_PIC_POLE3            1072
#define IDC_STATIC_PIC_POLE4            1073
#define IDC_STATIC_PIC_POLE5            1074
#define IDC_STATIC_PIC_POLE6            1075
#define IDC_STATIC_X_ZERO_POS           1076
#define IDC_BTN_PMove                   1077
#define IDC_STATIC_Y_ZERO_POS           1077
#define IDC_BTN_RALM                    1078
#define IDC_STATIC_Z_ZERO_POS           1078
#define IDC_BTN_MMove                   1079
#define IDC_EDIT_X_ZERO_POS             1079
#define IDC_BTN_MMove2                  1080
#define IDC_BTN_Rise                    1080
#define IDC_BTN_Middle                  1081
#define IDC_BTN_Start                   1082
#define IDC_EDIT_InitialStatus          1083
#define IDC_BTN_StopMe                  1084
#define IDC_BTN_Down                    1085
#define IDC_BTN_Rise2                   1086
#define IDC_BTN_Resetme                 1086
#define IDC_EDIT_InitialStatus2         1087
#define IDC_EDIT_Pose                   1087
#define IDC_EDIT_Pose2                  1088
#define IDC_EDIT_Pulse                  1088
#define IDC_EDIT_RC                     1088
#define IDC_EDIT_Sensor                 1089
#define IDC_EDIT_Y_ZERO_POS             1090
#define IDC_EDIT_Z_ZERO_POS             1091
#define IDC_STATIC_ROLL_ZERO_POS        1092
#define IDC_STATIC_PITCH_ZERO_POS       1093
#define IDC_STATIC_YAW_ZERO_POS         1094
#define IDC_EDIT_ROLL_ZERO_POS          1095
#define IDC_EDIT_PITCH_ZERO_POS         1096
#define IDC_EDIT_YAW_PHASE2             1097
#define IDC_EDIT_YAW_ZERO_POS           1097

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
